### PR TITLE
Add avatar_url to the Owner struct

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Review by christopher-dG — APPROVED** [review]

**Comment by ViralBShah** [comment]
I suspect the CI needs to be moved to gh-actions.

**Comment by mattBrzezinski** [comment]
> I suspect the CI needs to be moved to gh-actions.

https://travis-ci.com/github/JuliaWeb/GitHub.jl

It looks like it's chugging along.

**Comment by DilumAluthge** [comment]
That being said, we'll eventually need to move to GHA when the Travis credits run out.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaWeb/GitHub.jl/pull/175

**Comment by KristofferC** [comment]
I haven't seen that before. I restarted it.

**Pull request merged**
