### PR TITLE
Query All Users API and Pagination

### PR DESCRIPTION
**Pull request by sorpaas**
There are two things added in this pull request:

1. An API to query all users.
2. Better pagination support by directly returning next_page and last_page URL.

According to [GitHub](https://developer.github.com/v3/#link-header), it's better to follow the Link header rather than constructing URLs ourselves. For example, `/users` API always return next page link and previous page link using `since` rather than `page`. Thus it becomes impossible to get page number and page left, etc.

This is my first pull request to a Julia project, so please tell me if I got anything wrong.

### CODE REVIEW

**Comment by jrevels** [comment]
Hi, thanks for the contribution! 

> An API to query all users.

Looks good to me!

> Better pagination support by directly returning next_page and last_page URL...it's better to follow the Link header rather than constructing URLs ourselves.

This is slightly more tricky. Note that the old API wasn't constructing the `"next"` pagination URLs manually, but was rather parsing the links to determine whether or not to stop retrieving pages, then reporting this same info back to the user so they could use it to make decisions that can easily be fed back into the input needed by the API (e.g. `page`,  `page_limit` params take integers). It's still a bug, since the parsing can't be relied on, but I'd like the fix to enable the user can easily feed the `"next"` and `"last"` links we provide back into the paginated API methods.

Something like:

```julia
cs, pd = GitHub.commits("JuliaWeb/GitHub.jl", page_limit = 1)
cs2, pd2 = GitHub.commits("JuliaWeb/GitHub.jl", page_limit = 1, next_page = pd["next"])
cs3, pd3 = GitHub.commits("JuliaWeb/GitHub.jl", page_limit = 1, next_page = pd["last"])
```

This can be accomplished by adding the `next_page` keyword argument to the [`github_paged_request` method](https://github.com/sorpaas/GitHub.jl/blob/master/src/utils/requests.jl#L69). It would also be nice to keep the `"left"` key in the returned `page_data` if we can calculate the number of pages left from the returned links, and simply omit it when we can't. 

Again, thanks for identifying the bug and contributing back to the package!

**Comment by sorpaas** [comment]
Hi @jrevels,

I guess maybe we can keep compatibility by first detecting whether the page_request is separated by page. If so, then simply add another key `paged` to `pd`. So it is like:

```
pd["paged?"] == true
pd["next"] == 3
pd["last"] == 2
pd["left"] == 2
```

While if the paged_request not actually separated by page, then we use `next_page_param` and `last_page_param` for that.

```
pd["paged?"] == false
pd["next_page_param"] == "since=297"
pd["last_page_param"] == "since=0"
```

This allows some tricky APIs, like querying all users, to be implemented, while not breaking anything existing. If something like this seems fine, I'm going to implement that.

Looking forward to your comments!

**Comment by jrevels** [comment]
I actually prefer your original idea more, as long as we can also add the keyword arguments I mentioned in my previous comment. To summarize, I'm thinking `pd` would look like

```
results, pd = GitHub.some_paged_method(...)

pd["next"] == "https://...?page=3&per_page=100" # some url string
pd["last"] == "https://...?page=50&per_page=100" # some other url string
pd["left"] == 47 # included in pd only if "page" is the separator

results, nextpd = GitHub.some_paged_method(...; next_page = pd["next"])

nextpd["next"] == "https://...?page=4&per_page=100"
nextpd["last"] == "https://...?page=4&per_page=100"
nextpd["left"] == 46
```

Then, the only difference in the case where `"page"` is not the separator is that we don't include `"left"` in `pd`. 

If you'd like, we can merge this now (since it works as is) and I can add these changes myself later.

**Comment by sorpaas** [comment]
Hi Jarrett,

Yeah, since I'm suffering from limited Internet access until next month,
that would be great!

-- Wei

**Pull request merged**
