### PR TITLE
Load HDF5 on travis without sudo and hide 0.4 / show 0.6 pkg badge

### PR DESCRIPTION
**Pull request by KristofferC**
Also use String instead of UTF8String now when 0.4 support is dropped. Could rename GitHubString to String but not sure if that is wanted.

### CODE REVIEW

**Comment by KristofferC** [comment]
This should be fairly uncontroversial?

**Comment by jrevels** [comment]
> Could rename GitHubString to String but not sure if that is wanted.

That would be great, thanks (sorry for the late reply, I don't keep up with GitHub.jl too frequently).

**Comment by KristofferC** [comment]
Done

**Comment by KristofferC** [comment]
I sneaked in a `@testset` commit here as well. Hope that is ok.

**Comment by KristofferC** [comment]
Anything left to do here?

**Comment by jrevels** [comment]
Thanks again!

**Pull request merged**
