### PR TITLE
use idle_timeout for the requests

### PR DESCRIPTION
**Pull request by KristofferC**
cc @samoconnor

### CODE REVIEW

**Comment by KristofferC** [comment]
Test fails on 0.7, not because of this PR though:

```
EventListener: Test Failed at /home/travis/.julia/v0.7/GitHub/test/event_tests.jl:13
  Expression: GitHub.has_valid_secret(event_request, "secret")
Stacktrace:
 [1] macro expansion at /home/travis/.julia/v0.7/GitHub/test/event_tests.jl:13 [inlined]
 [2] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/site/v0.7/Test/src/Test.jl:1022 [inlined]
 [3] top-level scope at /home/travis/.julia/v0.7/GitHub/test/event_tests.jl:12
EventListener: Error During Test at /home/travis/.julia/v0.7/GitHub/test/event_tests.jl:18
  Expression evaluated to non-Boolean
  Expression: GitHub.handle_event_request(event_request, (x->begin
            true
        end), secret="secret", events=["commit_comment"], repos=["JuliaCI/BenchmarkTrackers.jl"])
       Value: HTTP.Messages.Response:
"""
HTTP/1.1 400 Bad Request
invalid signature"""
```

**Comment by samoconnor** [comment]
I'm running `Pkg.test("GitHub.jl")` with this branch on my local machine (macOS v0.6.2) now...

I've modified `runtests.jl` like this to see if the connection pooling / timeout is working:
```julia
for i in 1:10
    include("read_only_api_tests.jl")
    HTTP.ConnectionPool.showpool(STDOUT)
    sleep(40)
end
```

**Comment by KristofferC** [comment]
But the `read_only_api_tests` does not start any server so should be unaffected by this? Maybe I misunderstood something about where I should put this keyword, I thought it was a server setting (I know nothing about this stuff :D).

**Comment by samoconnor** [comment]
You will need `REQUIRE: HTTP 0.6.8` too (not tagged yet).

**Comment by samoconnor** [comment]
ok, no, the idle_timeout=20 is a `request` option.

**Comment by KristofferC** [comment]
Oh, oops!

**Comment by KristofferC** [comment]
Will fix

**Comment by KristofferC** [comment]
Updated to be a request option.

**Comment by samoconnor** [comment]
That seems to be working (note that the local socket number is different after the 2nd run):
```julia
Test Summary:       | Pass  Total
Tags and References |    1      1
ConnectionPool[
   ⏸   63↑    63↓    api.github.com:443:53937 ≣16
]

Test Summary: | Pass  Total
Owners        |    9      9
Test Summary: | Pass  Total
Repositories  |   16     16
Test Summary: | Pass  Total
Issues        |    4      4
Test Summary: | Pass  Total
Gists         |    5      5
Test Summary: | Pass  Total
Reviews       |    1      1
Test Summary: | Pass  Total
Activity      |    4      4
Test Summary: | Pass  Total
Apps          |    4      4
Test Summary: | Pass  Total
Git Data      |    4      4
Test Summary:       | Pass  Total
Tags and References |    1      1
ConnectionPool[
   ⏸   63↑    63↓    api.github.com:443:53939 ≣16
]
```

**Comment by samoconnor** [comment]
Before the change I aws seeing this:
```julia
Test Summary:       | Pass  Total
Tags and References |    1      1
ConnectionPool[
   ⏸   63↑    63↓    api.github.com:443:53854 ≣16
]

Test Summary: | Pass  Total
Owners        |    9      9
Test Summary: | Pass  Total
Repositories  |   16     16
Test Summary: | Pass  Total
Issues        |    4      4
Test Summary: | Pass  Total
Gists         |    5      5
Test Summary: | Pass  Total
Reviews       |    1      1
Test Summary: | Pass  Total
Activity      |    4      4
Test Summary: | Pass  Total
Apps          |    4      4
Test Summary: | Pass  Total
Git Data      |    4      4
Test Summary:       | Pass  Total
Tags and References |    1      1
ConnectionPool[
   ⏸  126↑   126↓    api.github.com:443:53854 ≣16
]
```

**Comment by KristofferC** [comment]
Ok, @ararslan, should we make Nanosoldier a guinea pig for this (in other words update HTTP and use this PR) or what do you prefer?

**Comment by samoconnor** [comment]
I'm just reviewing the diffs since last HTTP.jl tag now. I think I'm ok to tag, but I might be better to wait for @quinnj's input. It would probably be best to manually checkout this branch of GitHub.jl and master of HTTP.jl on nanosolidier to test.

**Comment by ararslan** [comment]
> should we make Nanosoldier a guinea pig for this (in other words update HTTP and use this PR) or what do you prefer?

That seems fine to me. There's actually a way to set up a test server for Nanosoldier but it's way more effort than just subjecting people to testing in production, so..................

**Comment by samoconnor** [comment]
I've reviewed the recent HTTP.jl changes. All the significant changes were already well reviewed in their respective PRs, and only take effect when new options are enabled, so it they seem pretty low risk. I've tagged HTTP.jl https://github.com/JuliaWeb/HTTP.jl/releases/tag/v0.6.8
But, I've left a note on the METADATA.jl PR to request that it not be merged right away.

**Comment by ararslan** [comment]
Nanosoldier seems to be running well using HTTP master and this branch of GitHub. There have only been a handful of triggered runs since this was set up, but there's been no ignoring and no `IOError`s.

**Comment by samoconnor** [comment]
@ararslan it would be a good idea to update the nanosolider box to use latest HTTP master to test this change: https://github.com/JuliaWeb/HTTP.jl/commit/fa6b20617ef2c0ee68e2415d348c04839a792e4e
The change reverts one of the things we tried in an attempt to reduce the nanosolider post retry problem. I believe that with GitHub.jl now using `idle_timeout` the original change is redundant (and it appears to cause problems elsewhere).

**Comment by samoconnor** [comment]
This looks good to be merged to me (but I don't have commit access here).

**Comment by samoconnor** [comment]
Looks like travis passes for 0.6 but not for 0.7.

New HTTP version is tagged and waiting for METADATA PR: https://github.com/JuliaLang/METADATA.jl/pull/14286

**Comment by KristofferC** [comment]
Passes on 0.7 now but needs new tag of MbedTLS (https://github.com/JuliaWeb/MbedTLS.jl/pull/137)

**Comment by Keno** [comment]
What's the status of this?

**Comment by KristofferC** [comment]
Not sure if this is still needed after all the new stuff in HTTP.jl.

**Comment by samoconnor** [comment]
I think if the github API is known to dump connections after x seconds, then having idle_timeout=x * some_fraction is the right thing to do, event if other changes in HTTP.jl improved the automatic retry behaviour.
This PR seems to have a bunch of 0.7 compat stuff too.

**Comment by KristofferC** [comment]
A few more dep warnings now but this is a step in the right direction.

**Pull request merged**
